<a href="https://colab.research.google.com/github/AndreAEAA/Repositorio_IA/blob/main/Tarea1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

df= pd.read_csv('./ventas.csv')

df.head()

    Producto  Cantidad  Precio_Unitario
0     Webcam        15               74
1    Monitor        19              866
2  Impresora        12              848
3     Webcam         3              530
4    Teclado         5              353

In [4]:
Categoria = df.groupby("Producto")["Cantidad"].sum()

Categoria.head()

Producto
Auriculares     53
Impresora       65
Laptop          49
Monitor        113
Mouse           55
Name: Cantidad, dtype: int64

In [5]:

ProductoMasVendido= Categoria.idxmax()



print("\n Producto Mayor total de ventas:", ProductoMasVendido)

 Producto Mayor total de ventas: Monitor

In [6]:
PrecioPromedio= df["Precio_Unitario"].mean()

print("\n Precio de los productos vendidos:", PrecioPromedio)

 Precio de los productos vendidos: 501.82

In [7]:
import pandas as pd

CLIMA = pd.read_csv('./clima.csv')

CLIMA.head()

        Fecha            Ciudad  Temperatura
0  2023-01-01            Bogotá        25.84
1  2023-01-02          Santiago        14.75
2  2023-01-03            Madrid        15.91
3  2023-01-04            Madrid        12.10
4  2023-01-05  Ciudad de México        -3.98

In [8]:
tempromedio =CLIMA.groupby("Ciudad")["Temperatura"].mean()

tempromedio.head()

Ciudad
Bogotá              14.650794
Buenos Aires        15.226571
Ciudad de México    17.250833
Madrid              13.870000
Santiago            13.993718
Name: Temperatura, dtype: float64

In [9]:
temp_max =CLIMA.loc[CLIMA["Temperatura"].idxmax()]
temp_max.head()

Fecha          2023-10-24
Ciudad             Madrid
Temperatura         34.62
Name: 296, dtype: object

In [10]:
temp_min = CLIMA.loc[CLIMA["Temperatura"].idxmin()]
temp_min.head()

Fecha          2023-04-25
Ciudad             Madrid
Temperatura          -4.8
Name: 114, dtype: object

In [11]:
temp_max30 = (CLIMA["Temperatura"] > 30).sum()

print(f"\n  Temperatura mayor a 30°C fue de: {temp_max30}")

  Temperatura mayor a 30°C fue de: 50

In [12]:
diasciudad = CLIMA["Ciudad"].value_counts()
print("\n Cantidad de días registrados por ciudad:")

diasciudad.head()

 Cantidad de días registrados por ciudad:

Ciudad
Madrid              82
Santiago            78
Ciudad de México    72
Buenos Aires        70
Bogotá              63
Name: count, dtype: int64

In [13]:
import pandas as pd

df = pd.read_csv('./calificaciones.csv')

df.head()

      Estudiante      Materia  Calificación
0   Estudiante_7         Arte            99
1  Estudiante_51  Matemáticas            55
2  Estudiante_72  Matemáticas            58
3  Estudiante_42  Matemáticas            82
4  Estudiante_64       Inglés            90

In [17]:
promedio_materia = df.groupby("Materia")["Calificación"].mean()
print("\nPromedio por materia:")
print(promedio_materia)

Promedio por materia:
Materia
Arte           74.823529
Ciencias       73.712766
Historia       73.087379
Inglés         72.740385
Matemáticas    73.659794
Name: Calificación, dtype: float64

In [29]:

estudiante = promedio_estudiante.idxmax()
print(f"\nEstudiante con el promedio más alto: {estudiante} ({promedio_estudiante[estudiante_top]:.2f})")

Estudiante con el promedio más alto: Estudiante_84 (96.00)

In [23]:
promedio_estudiante = df.groupby("Estudiante")["Calificación"].mean()
print("\nPromedio por estudiante:")
print(promedio_estudiante)

Promedio por estudiante:
Estudiante
Estudiante_1      79.428571
Estudiante_10     80.600000
Estudiante_100    60.000000
Estudiante_11     75.000000
Estudiante_12     65.000000
                    ...
Estudiante_95     85.500000
Estudiante_96     59.500000
Estudiante_97     86.400000
Estudiante_98     76.571429
Estudiante_99     67.000000
Name: Calificación, Length: 99, dtype: float64

In [25]:
mayor_85 = promedio_estudiante[promedio_estudiante > 85]
print(f"\nCantidad de estudiantes con promedio superior a 85: {len(mayor_85)}")

Cantidad de estudiantes con promedio superior a 85: 5

In [27]:
materia_calificaciones = df["Materia"].value_counts().idxmax()
print(f"\nMateria con más calificaciones registradas: {materia_calificaciones}")

Materia con más calificaciones registradas: Inglés

In [28]:
mas_bajo = promedio_estudiante.sort_values().head(5)
print("\n5 estudiantes con el promedio más bajo:")
print(mas_bajo)

5 estudiantes con el promedio más bajo:
Estudiante
Estudiante_79    51.0
Estudiante_58    57.0
Estudiante_91    58.0
Estudiante_50    59.0
Estudiante_80    59.0
Name: Calificación, dtype: float64